name: Formalization website
on:
  # To run this workflow manually
  workflow_dispatch:
    inputs:
      ref:
        description: the repository ref to build
        required: true
        default: master

  push:
    branches:
      - master

# Cancel previous runs of the same branch
concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.run_id }}'
  cancel-in-progress: true

env:
  AGDAHTMLFLAGS:
    --html --html-highlight=auto --html-dir=docs --only-scope-checking
    --css=Agda.css
  AGDA: agda
jobs:
  website:
    runs-on: macOS-latest
    strategy:
      matrix:
        agda: ['2.6.3']
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    steps:
      - name: Checkout our repository
        uses: actions/checkout@v3
        with:
          path: master

      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '3.0.1'

      - name: Setup Agda
        uses: wenkokke/setup-agda@v2.0.0
        with:
          agda-version: ${{ matrix.agda }}

      - uses: actions/cache/restore@v3
        id: cache-agda-formalization
        name: Restore Agda formalization cache
        with:
          path: master/_build
          key:
            ${{ runner.os }}-check-${{ github.ref }}-${{ matrix.agda }}-${{
            hashFiles('master/src/**') }}
          restore-keys: |
            ${{ runner.os }}-check-${{ github.ref }}-${{ matrix.agda }}-

      - name: MDBook setup
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - name: Install mdbook-pagetoc
        uses: baptiste0928/cargo-install@v2
        with:
          crate: mdbook-pagetoc

      - name: Install mdbook-katex
        uses: baptiste0928/cargo-install@v2
        with:
          crate: mdbook-katex

      - name: Install mdbook-linkcheck
        uses: baptiste0928/cargo-install@v2
        with:
          crate: mdbook-linkcheck

      - name: Install mdbook-catppuccin
        uses: baptiste0928/cargo-install@v2
        with:
          crate: mdbook-catppuccin

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.1'
          check-latest: true
          cache: 'pip'

      - run: python3 -m pip install -r master/scripts/requirements.txt

      - name: Generate book
        run: |
          cd master
          make website

      - name: Setup Pages
        uses: actions/configure-pages@v3
        if: >-
          github.ref == 'refs/heads/master' || github.event_name ==
          'workflow_dispatch'

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        if: >-
          github.ref == 'refs/heads/master' || github.event_name ==
          'workflow_dispatch'
        with:
          path: master/book/html

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        id: deployment
        if: >-
          github.ref == 'refs/heads/master' || github.event_name ==
          'workflow_dispatch'
